"use strict";

exports.APP_NOTIFICATION_TEMPLATE = "APP_NOTIFICATION_TEMPLATE";
exports.EMAIL_NOTIFICATION_TEMPLATE = "EMAIL_NOTIFICATION_TEMPLATE";
exports.SMS_NOTIFICATION_TEMPLATE = "SMS_NOTIFICATION_TEMPLATE";
exports.TEMPLATE_TYPES = ["APP_NOTIFICATION_TEMPLATE", "EMAIL_NOTIFICATION_TEMPLATE", "SMS_NOTIFICATION_TEMPLATE"];

exports.ANDROID_TOKEN = "ANDROID_TOKEN";
exports.IOS_TOKEN = "IOS_TOKEN";
exports.WEB_TOKEN = "WEB_TOKEN";
exports.EMAIL_TOKEN = "EMAIL_TOKEN";
exports.SMS_TOKEN = "SMS_TOKEN";
exports.TOKEN_TYPES = ["ANDROID_TOKEN", "IOS_TOKEN", "WEB_TOKEN", "EMAIL_TOKEN", "SMS_TOKEN"];
exports.CREATESUBSCRIBER = "CREATESUBSCRIBER";
exports.READSUBSCRIBER = "READSUBSCRIBER";
exports.DELETESUBSCRIBER = "DELETESUBSCRIBER";
exports.CREATEEVENT = "CREATEEVENT";

exports.BASE_URL = "http://localhost:3020/api";